import Buy from "./buy";
import ShoppingCart from "./shopping-cart";
import User from "./user";
import Fabric from "./fabric";
import Location from "./location";
import Phone from "./phone";
import Email from "./email";
import LocalComertial from "./local-comercial";
import Instagram from "./instagram";
import Facebook from "./facebook";
import BackArrow from "./back";
import NextArrow from "./next";
export { Buy, ShoppingCart, User, Fabric, Location, Phone, Email, LocalComertial, Instagram, Facebook, BackArrow, NextArrow };