import type { Metadata } from 'next';
import './globals.css';

import { Raleway } from 'next/font/google';
import Footer from '@/components/footer/footer';
import Header from '@/components/header/header';
import Link from 'next/link';
import { Facebook, Instagram } from '@/app/assets/icons';
import { Youtube, LinkedIn } from '@/components/icons';
import { CotizacionWidget } from '@/components/cotizacion-widget';

const raleway = Raleway({
  subsets: ['latin'],
  variable: '--font-raleway',
});

export const metadata: Metadata = {
  title: 'Aisplac',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Header />

        <main className="relative">
          {children}
          <div className="absolute bottom-0 flex w-full items-center justify-center gap-2 py-10 md:gap-4">
            <Link
              href="https://www.youtube.com/@aisplacsrl"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center"
            >
              <Youtube className="h-14 w-14 hover:text-red-500" />
            </Link>
            <Link
              href="https://www.linkedin.com/in/aisplacsrl/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <LinkedIn className="h-14 w-14 hover:text-red-500" />
            </Link>
            <Link
              href="https://www.instagram.com/aisplacsrl/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Instagram className="h-14 w-14 hover:text-red-500" />
            </Link>
            <Link
              href="https://www.facebook.com/Aisplac"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Facebook className="h-14 w-14 hover:text-red-500" />
            </Link>
          </div>
        </main>
        <CotizacionWidget />

        <Footer />
      </body>
    </html>
  );
}
