import type { Metadata } from "next";
import "./globals.css";

import { Raleway } from "next/font/google";
import Footer from "@/components/footer/footer";
import Link from "next/link";
import { Facebook, Instagram } from "./assets/icons";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        {children}
        <div className="bg-[#100E1F] w-full flex justify-center  py-10  items-center gap-4">
          <Link
            href="https://www.instagram.com/aisplacsrl/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Instagram className="w-20 h-20 hover:text-red" />
          </Link>
          <Link
            href="https://www.facebook.com/Aisplac"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Facebook className="w-20 h-20" />
          </Link>
        </div>
        <Footer />
      </body>
    </html>
  );
}
