import type { Metadata } from "next";
import "./globals.css";

import { Raleway } from "next/font/google";
import Footer from "@/components/footer/footer";
import Header from "@/components/header/header"; // 💡 cambio: importamos el Header
import Link from "next/link";
import { Facebook, Instagram } from "@/app/assets/icons";
import { Youtube, LinkedIn } from "@/components/icons";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Header />
        <main className="relative">
          {children}
          <div className="absolute bottom-0 w-full flex flex-wrap justify-center py-10 items-center gap-2 md:gap-4">
            <Link
              href="https://www.instagram.com/aisplacsrl/"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center"
            >
              <Youtube className="w-8 h-8 sm:w-10 sm:h-10 md:w-14 md:h-14 hover:text-red-500" />
            </Link>
            <Link
              href="https://www.linkedin.com/in/aisplacsrl/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <LinkedIn className="w-8 h-8 sm:w-10 sm:h-10 md:w-14 md:h-14 hover:text-red-500" />
            </Link>
            <Link
              href="https://www.instagram.com/aisplacsrl/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Instagram className="w-8 h-8 sm:w-10 sm:h-10 md:w-14 md:h-14 hover:text-red-500" />
            </Link>
            <Link
              href="https://www.facebook.com/Aisplac"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Facebook className="w-8 h-8 sm:w-10 sm:h-10 md:w-14 md:h-14 hover:text-red-500" />
            </Link>
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
